name: shelf_dev
version: 1.0.0
repository: https://github.com/kevmoo/shelf_dev/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  build_cli_annotations: ^2.0.0
  checked_yaml: ^2.0.1
  http: ^0.13.0
  io: ^1.0.0
  json_annotation: ^4.0.0
  path: ^1.7.0
  shelf: ^1.0.0
  shelf_proxy: ^1.0.0
  stack_trace: ^1.10.0

dev_dependencies:
  async: ^2.5.0
  build_cli: ^2.1.1
  build_runner: ^1.0.0
  build_verify: ^2.0.0
  build_version: ^2.0.2
  json_serializable: ^4.0.2
  pedantic: ^1.9.0
  # Needed because we are configuring `combining_builder`
  source_gen: ^1.0.0
  test: ^1.6.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0

executables:
  shelf_dev:
